import fs from 'node:fs';
import path from 'node:path';
import { detectProject } from '../core/detectProject.js';
import { buildManifest } from '../core/safety.js';
import { generatePlan } from '../core/generatePlan.js';
import { ProfileId } from '../core/profile.js';

const targets = [
  'README.md','PROMPT.md','.github/PULL_REQUEST_TEMPLATE.md',
  'docs/core/evidence-policy.md','docs/core/quality-gates.md','docs/core/security-policy.md'
];

export function initCommand(opts: { profile?: ProfileId; dryRun?: boolean }) {
  const cwd = process.cwd();
  const detected = detectProject(cwd);
  const profile = opts.profile || detected.profile;
  const manifest = buildManifest(targets.map((t) => path.join(cwd, t)));
  console.log('Detected profile:', detected.profile, 'signals:', detected.signals.join(', ') || 'none');
  console.log('Using profile:', profile);
  console.log('Plan:', generatePlan(profile));
  console.log('Manifest:');
  manifest.forEach((m) => console.log('-', path.relative(cwd, m.path), m.status));
  if (opts.dryRun) return;
  for (const m of manifest) {
    if (m.status === 'skip-conflict') continue;
    fs.mkdirSync(path.dirname(m.path), { recursive: true });
    fs.writeFileSync(m.path, '# generated by create-ai-native-dev\n');
  }
}
